---
- hosts: nodes
  remote_user: pi
  become: yes

  tasks:
    - name: apt-get update
      apt: update_cache=yes cache_valid_time=3600

    - name: Update all packages to the latest version
      apt: upgrade=dist
