---
- hosts: all
  remote_user: pi
  tasks:
    - name: 1. install Apache
      apt: name=apache2 state=absent
      become: yes
      become_method: sudo

    - name: 2. install PHP module for Apache
      apt: name=libapache2-mod-php5 state=absent
      become: yes
      become_method: sudo

    - name: 3. start Apache
      service: name=apache2 state=stopped enabled=no
      become: yes
      become_method: sudo

    - name: 4. install Hello World PHP script
      copy: src=index.php dest=/var/www/index.php mode=0664
      become: yes
      become_method: sudo
