---
- hosts: nodes
  remote_user: pi
  become: yes

  tasks:
    - name: Install list of packages
      apt: update_cache=yes cache_valid_time=3600 pkg={{item}} state=installed autoremove=yes
      with_items:
       - curl
       - dnsutils
       - git
       - htop
       - mlocate
       - oracle-java8-jdk
       - rpi-update
       - screen
       - wget

    - name: Remove list of packages
      apt: update_cache=yes cache_valid_time=3600 pkg={{item}} state=absent purge=yes autoremove=yes
      with_items:
       - bluez
       - docker.io
       - openjdk-7-jre
       - openjdk-7-jre-headless
       - wireless-tools

    - name: Some build tools
      apt: update_cache=yes cache_valid_time=3600 pkg={{item}} state=installed autoremove=yes
      with_items:
       - cpp
       - dh-autoreconf
       - g++
       - gcc 
       - libapr1-dev
       - libcurl4-openssl-dev
       - libsasl2-dev
       - libsvn-dev
       - maven
       - python-dev
       - libcgroup1
       - cgmanager

  vars: 
  - consul_atlas_join: false
  - consul_bootstrap_expect: 3
  - consul_datacenter: "lon"
  - consul_server: true
  - consul_web_ui: true
  - consul_with_dnsmasq: false
  - mesos_slave: true
  - mesos_master: true
  - mesos_quorum: 3
  
  roles:
    - consul 
    - docker
    - environment
    - zookeeper
    - mesos
    - marathon
