---
- hosts: nodes
  remote_user: pi
  become: yes

  tasks:
    - name: Install list of packages
      apt: update_cache=yes cache_valid_time=3600 pkg={{item}} state=installed autoremove=yes
      with_items:
       - rpi-update
       - git
       - screen
       - curl
       - wget
       - mlocate
