---
# Ensure SNMPD is installed
- name: installing snmpd
  apt: name=snmpd state=present
  when: ansible_os_family == "Debian"

# Copy configuration
- name: copying snmpd config
  template: src=snmpd.conf.j2 dest=/etc/snmp/snmpd.conf owner=root group=root mode=0644
  when: config_snmpd
  notify: restart snmpd

# Start and enable service
- name: starting and enabling snmpd service
  service: name=snmpd enabled=yes state=started

